### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by Blash** [SpellholdStudios/DSotSC#12]
Hello, here is an error I found twice:

ADD_WORLDMAP_TBL: 4 areas and 15 links added to worldmap.wmp
Creating 1 directory
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC007.TBC", output: "DSotSC\biff\DSC007.tis"
Error while converting "DSotSC\base\tis\DSC007.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC009.TBC", output: "DSotSC\biff\DSC009.tis"
Error while converting "DSotSC\base\tis\DSC009.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC035.TBC", output: "DSotSC\biff\DSC035.tis"
Error while converting "DSotSC\base\tis\DSC035.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC037.TBC", output: "DSotSC\biff\DSC037.tis"
Error while converting "DSotSC\base\tis\DSC037.TBC"

And again:

Creating 1 directory
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC007.TBC", output: "DSotSC\biff\DSC007.tis"
Error while converting "DSotSC\base\tis\DSC007.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC009.TBC", output: "DSotSC\biff\DSC009.tis"
Error while converting "DSotSC\base\tis\DSC009.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC035.TBC", output: "DSotSC\biff\DSC035.tis"
Error while converting "DSotSC\base\tis\DSC035.TBC"
Options: pixel encoding = BC1/DXT1 (zlib-compressed), halt on errors = disabled, verbosity level = default, decoding quality = 4, encoding quality = 9, convert MBC to MOS, headerless TIS not allowed, jobs = 12
Converting TBC -> TIS
Input: "DSotSC\base\tis\DSC037.TBC", output: "DSotSC\biff\DSC037.tis"
Error while converting "DSotSC\base\tis\DSC037.TBC"

**Comment by Gitjas** [comment]
Thanks, the tis wasn't extracted to the override at all. Will be fixed in v3.2
