### ISSUE TITLE
TIS in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [SpellholdStudios/DSotSC#14]
The crash of DSC007, 009, 035 or 037 no longer happens due to missing Tis files.
However, the Tis is only in old format and not converted to PVRZ for EE. This is not an issue for the 2 smaller areas but annoying for the 2 larger ones.
Maybe the best solution would be to rather point to existing Tis files in the WED, because the areas use graphics that already exist in the game and there is no real need to add them once more (talking of EET).

**Comment by Gitjas** [comment]
This sounds like a good idea. Do you have the tis names of the areas ready and can post them here?

**Comment by Gitjas** [comment]
Hm, after checking I don't see these areas to be in the game already, it's edited versions of ingame areas. I'll add PVRZ tis versions for EET.

**Comment by Gitjas** [comment]
Areas now have PVRZ tis for EET.
