### ISSUE TITLE
DSotSC: Dave NPC Conflicts with Glam's NPC Pack and Ascalon's Questpack

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/DSotSC#16]
Greetings, jastey!

According to Big World Setup...

DSotSC/Glam's NPC Pack: "Dave NPC bugs Idol of Koszah: NTotSC or SandrahNPC or DSotSC or Vault is conflicting with GlamNPCPack."  I have the Vault mod selected but not Sandrah.

DSotSC/Ascalons Questpack: "Dave NPC bugs High Hedge and Thalantyr: AC_QUEST or Thalantyr is conflicting with GlamNPCPack."

(Note that Dark Side of the Sword Coast in BWS is considered a dependency of Northern Tales of the Sword Coast.)

May we get these fixed?

Thankee!

**Comment by Gitjas** [comment]
As I said elsewhere, BWS is highly outdated. Just in case you are referring to EE Setup Tool and not BWS - that's not "BWS", please do not call it that.
NTotSC is no longer depending on DSotSC for a long time now.
Ascalon's Questpack conflicts with Glam's NPC Pack insofar as that both mods use the hut in High Hedge, I am aware of the conflict.
I have no idea what "Dave NPC bugs Idol of Koszah" is supposed to mean.

**Comment by Endarire** [comment]
To clarify, does DSotSC use the Idol of Koszah (the name or item ID) somewhere?  The NPC named Dave or "Dave" as an NPC name?

Also, to clarify, this information was obtained in Roxanne's EET Setup Tool, not the old Big World Setup Tool.

**Comment by Gitjas** [comment]
DSotSC? Neither. I don't know why Roxanne still links DSotSC to NTotSC, this is completely outdated, the mods are not dependent on each other. Only thing is that if you want to have both, install DSotSC first.

NTotSC on the other hand has a quest where the Vampiric Sword ("Vampire's Revenge", SW1H19.itm) can be used to free three spirits. The Vampiric Sword is gained with the Idol of Kozah and the old armor from the Firewine Ruins by giving it to Ulcaster's ghost.
For me, this is less of a "mod conflict" than an ingame RPG problem: will you use the idol for the sword? Will you then use it to free the spirits? Or will you leave the idol to Dave for his improved item of Talos?
Not to mention that the three spirits can also be freed by killing them in a fight, a choice they accept just as much as the sword.

It's good if players are aware of this so they do have a choice and not just go with the first opportunity to use the idol. But even if they don't, this is no mod conflict in the sense of an incompatibility for which installation of both mods need to be prevented.

There was the suggestion NTotSC inserst a second Idol of Kozah just as it does for the old armor, but I am not fond of this idea. The idol is something pretty special, with driving all workers mad and provoking the Doomslayer if you take it.
This will just remain something the player has to decide which path to go.
