### ISSUE TITLE
Request: Use OlvynChuru's Class Spell Tool on the new spells to bypass the 50 spells per level limit.

### ISSUE THREAD

**Issue by Endarire** [SpellholdStudios/DSotSC#17]
Greetings!

OlvynChuru recently released [this tool](https://forums.beamdog.com/discussion/80718/tool-adding-class-or-kit-specific-spells) to easily avoid the 50 spells per type (arcane/divine) per spell level.  Since this tool only works for EE games, my request is to use this tool and upload a new version that works with this tool for EE- and EET-specific installs.

Thankee!

**Comment by GraionDilach** [comment]
This was resolved with #23 .
